name: wallpaper_app
description: Wallpaper App


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI Utility
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^1.0.3
  
  #Animation
  rive: ^0.8.1


  #State Management
  provider: ^6.0.2

  #Localization
  easy_localization: ^3.0.0
  
  #Local Storage
  shared_preferences: ^2.0.12

  #Network
  dio: ^4.0.4

  #Core Utility
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  url_launcher: ^6.0.18
  freezed_annotation: ^1.1.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/lang/
    - assets/animations/swipe_up.riv
    - assets/animations/firework.riv
    - assets/svg/turkey.svg
    - assets/svg/united-states.svg
    - assets/error/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
     
